server:
  port: 3002

spring:
  application:
    name: lighting-store
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      host: localhost
      port: 27017
      database: lights_store
      auto-index-creation: true
#      authentication-database: admin
#      username: root
#      password: rootpassword
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT Configuration
jwt:
  secret: 3bb8b2c9a1e4f5a7b6c4d3e2f6a7b8c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6
  expiration: 86400000 # 24 hours

# MinIO Configuration
minio:
  endpoint: http://localhost:9000
  access-key: prj_python
  secret-key: 12345678
  bucket-name: images

# Mail Configuration
mail:
  host: smtp.gmail.com
  port: 587
  username: toanxm1509@gmail.com
  password: bhxj pqnc eebw xgrb
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
        ssl:
          trust: smtp.gmail.com

logging:
  level:
    com.lighting: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: DEBUG
